stages:
  - build
  - test

build_job:
  stage: build
  image: debian:bullseye
  before_script:
    - apt-get update
    - apt-get install -y build-essential pkg-config libglib2.0-dev libjson-glib-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev libgstrtspserver-1.0-dev libsoup2.4-dev libzmq3-dev libcmocka-dev
  script:
    - chmod +x ./scripts/build_on_board.sh
    - ./scripts/build_on_board.sh

test_job:
  stage: test
  image: debian:bullseye
  before_script:
    - apt-get update
    - apt-get install -y build-essential pkg-config libglib2.0-dev libjson-glib-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev libgstrtspserver-1.0-dev libsoup2.4-dev libzmq3-dev libcmocka-dev meson ninja
  script:
    - chmod +x ./scripts/build_tests.sh
    - ./scripts/build_tests.sh
