/*
 * web_assets.h — Embedded Web Dashboard Assets (Professional SPA)
 * ==================================================================
 * Robust, production-grade Management Dashboard for SmartIP Edge.
 * Handles: Auth, HLS Playback, Dynamic Tuning, Lens Config, etc.
 */

#ifndef SMARTIP_WEB_ASSETS_H
#define SMARTIP_WEB_ASSETS_H

static const char *dashboard_html = 
"<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>SmartIP Edge | Command Center</title>"
"<script src='https://cdn.jsdelivr.net/npm/hls.js@latest'></script>"
"<link href='https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap' rel='stylesheet'>"
"<style>"
"  :root { --bg: #0f172a; --card: #1e293b; --accent: #10b981; --accent-hover: #059669; --text: #f8fafc; --text-dim: #94a3b8; --border: #334155; --danger: #ef4444; }"
"  * { box-sizing: border-box; margin: 0; padding: 0; }"
"  body { background: var(--bg); color: var(--text); font-family: 'Inter', sans-serif; display: flex; height: 100vh; overflow: hidden; }"
"  a { color: inherit; text-decoration: none; }"
"  button { cursor: pointer; border: none; font-family: inherit; transition: all 0.2s; padding: 10px 20px; border-radius: 8px; font-weight: 600; }"
"  input, select { background: #0f172a; border: 1px solid var(--border); color: white; padding: 10px 14px; border-radius: 8px; font-family: inherit; outline: none; }"
"  input:focus, select:focus { border-color: var(--accent); }"
"  /* Sidebar */"
"  nav { width: 280px; background: #0b1120; border-right: 1px solid var(--border); padding: 32px 24px; display: flex; flex-direction: column; }"
"  .logo { font-size: 1.4rem; font-weight: 800; margin-bottom: 48px; color: var(--accent); display: flex; align-items: center; gap: 10px; letter-spacing: -0.5px; }"
"  .nav-item { padding: 14px 18px; border-radius: 12px; margin-bottom: 10px; color: var(--text-dim); display: flex; align-items: center; gap: 14px; cursor: pointer; font-weight: 500; transition: background 0.2s; }"
"  .nav-item:hover { background: rgba(255,255,255,0.05); color: white; }"
"  .nav-item.active { background: var(--accent); color: white; box-shadow: 0 4px 12px rgba(16, 185, 129, 0.2); }"
"  .logout { margin-top: auto; color: var(--danger); opacity: 0.8; }"
"  .logout:hover { opacity: 1; }"
"  /* Main Content */"
"  main { flex: 1; overflow-y: auto; padding: 48px; position: relative; }"
"  section { display: none; max-width: 1200px; margin: 0 auto; }"
"  section.active { display: block; animation: slideUp 0.4s cubic-bezier(0, 0, 0.2, 1); }"
"  @keyframes slideUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }"
"  /* Live View */"
"  .stream-header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 24px; }"
"  .stream-badge { background: var(--danger); padding: 4px 12px; border-radius: 99px; font-size: 0.7rem; font-weight: 800; text-transform: uppercase; letter-spacing: 1px; display: flex; align-items: center; gap: 6px; }"
"  .stream-badge.live { background: var(--accent); }"
"  .dot { width: 6px; height: 6px; background: white; border-radius: 50%; animation: pulse 1s infinite; }\n"
"  @keyframes pulse { 0% { opacity: 1; } 50% { opacity: 0.4; } 100% { opacity: 1; } }\n"
"  .stream-tabs { display: flex; gap: 10px; }"
"  .tab-btn { background: var(--card); border: 1px solid var(--border); color: var(--text-dim); padding: 10px 20px; border-radius: 10px; font-size: 0.875rem; transition: all 0.3s; }"
"  .tab-btn.active { border-color: var(--accent); color: var(--accent); background: rgba(16, 185, 129, 0.1); }"
"  .video-wrapper { position: relative; width: 100%; max-height: 80vh; background: #000; border-radius: 20px; overflow: hidden; border: 1px solid var(--border); box-shadow: 0 20px 25px -5px rgba(0,0,0,0.5); display: flex; justify-content: center; align-items: center; }"
"  video { width: 100%; max-height: 100%; object-fit: contain; display: block; }"
"  .top-overlay { position: absolute; top: 20px; left: 20px; right: 20px; display: flex; justify-content: space-between; pointer-events: none; }"
"  .overlay-btn { pointer-events: auto; background: rgba(15, 23, 42, 0.6); backdrop-filter: blur(12px); border: 1px solid rgba(255,255,255,0.1); color: white; padding: 10px 16px; border-radius: 10px; font-size: 0.8rem; }"
"  .overlay-btn:hover { background: var(--accent); border-color: var(--accent); }\n"
"  /* Controls */"
"  .card { background: var(--card); border: 1px solid var(--border); border-radius: 20px; padding: 32px; margin-bottom: 24px; }\n"
"  .ctrl-grid { display: grid; grid-template-columns: 1.5fr 1fr; gap: 32px; margin-top: 32px; }\n"
"  .form-group { margin-bottom: 24px; }\n"
"  .form-group label { display: block; margin-bottom: 10px; font-size: 0.85rem; font-weight: 600; color: var(--text-dim); text-transform: uppercase; letter-spacing: 0.5px; }\n"
"  .range-wrap { display: flex; align-items: center; gap: 15px; }\n"
"  input[type=range] { flex: 1; accent-color: var(--accent); }\n"
"  .stat-row { display: flex; justify-content: space-between; padding: 12px 0; border-bottom: 1px solid rgba(255,255,255,0.05); font-size: 0.9rem; }\n"
"  .stat-label { color: var(--text-dim); }\n"
"  /* Recordings */"
"  .recordings-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 24px; }\n"
"  .rec-card { background: var(--card); border: 1px solid var(--border); border-radius: 16px; padding: 20px; transition: transform 0.2s; }\n"
"  .rec-card:hover { transform: translateY(-4px); border-color: var(--accent); }\n"
"  #login-overlay { position: fixed; inset: 0; background: #020617; z-index: 1000; display: flex; align-items: center; justify-content: center; }"
"</style></head><body>"
"  <div id='login-overlay'>"
"    <div class='card' style='width:420px; padding:48px; text-align:center; border-color:var(--accent)'>"
"      <div class='logo' style='justify-content:center; margin-bottom:32px'>SMARTIP EDGE</div>"
"      <h2 style='margin-bottom:32px; font-weight:700'>System Login</h2>"
"      <div class='form-group'><input type='text' id='user' placeholder='Username' style='width:100%'></div>"
"      <div class='form-group'><input type='password' id='pass' placeholder='Password' style='width:100%'></div>"
"      <button style='width:100%; background:var(--accent); color:white' onclick='doLogin()'>Authorize Access</button>"
"      <p id='login-error' style='color:var(--danger); margin-top:20px; font-size:0.875rem; font-weight:500; display:none'>Access Denied: Invalid Credentials</p>"
"    </div>"
"  </div>"
"  <nav>"
"    <div class='logo'><span style='color:white'>Smart</span>IP</div>"
"    <div class='nav-item active' onclick=\"switchTab('live')\">Dashboard</div>"
"    <div class='nav-item' onclick=\"switchTab('config')\">Configuration</div>"
"    <div class='nav-item' onclick=\"switchTab('recordings')\">Recordings</div>"
"    <div class='nav-item' onclick=\"switchTab('advanced')\">System Log</div>"
"    <div class='nav-item logout' onclick='logout()'>Sign Out</div>"
"  </nav>"
"  <main>"
"    <section id='live' class='active'>"
"      <div class='stream-header'>"
"        <div><h2 id='current-stream-title' style='margin-bottom:4px'>Global Live View</h2><div class='stream-tabs' id='stream-selector'></div></div>"
"        <div style='display:flex; gap:15px; align-items:center'>"
"          <div style='font-size:0.85rem; color:var(--text-dim)'><span id='total-clients' style='font-size:1.1rem; color:white; font-weight:700'>0</span> RTSP Viewers</div>"
"          <div class='stream-badge live'><div class='dot'></div>LIVE <span id='stream-timer' style='margin-left:4px'>00:00:00</span></div>"
"        </div>"
"      </div>"
"      <div class='video-wrapper'>"
"        <div class='top-overlay'>"
"          <div style='display:flex;gap:10px'><div class='overlay-btn' id='overlay-info'>1080p | 25 FPS</div></div>"
"          <div style='display:flex;gap:10px'>"
"            <button class='overlay-btn' onclick='takeSnapshot()'>📷 PHOTO</button>"
"            <button class='overlay-btn' id='rec-toggle-btn' onclick='toggleRecording()'>● RECORD</button>"
"          </div>"
"        </div>"
"        <video id='video' controls autoplay muted></video>"
"      </div>"
"      <div class='ctrl-grid'>"
"        <div class='card'><h4>Live Tuning</h4><p style='color:var(--text-dim);font-size:0.8rem;margin-bottom:24px'>Calibrate encoder parameters in real-time.</p>"
"          <div class='form-group'><label>Target Bitrate</label><select id='tune-bitrate' style='width:100%' onchange='updateParams()'><option value='4000000'>4.0 Mbps (High Quality)</option><option value='2000000' selected>2.0 Mbps (Standard)</option><option value='1000000'>1.0 Mbps (Efficiency)</option><option value='500000'>500 kbps (Low Bandwidth)</option></select></div>"
"          <div class='form-group'><label>Resolution (CapsFilter)</label><select id='tune-res' style='width:100%' onchange='updateParams()'><option value=''>Keep Original</option><option value='1920x1080'>1080p Full HD</option><option value='1280x720'>720p HD</option><option value='640x480'>480p SD</option></select></div>"
"          <div class='form-group'><label>Output Framerate</label><div class='range-wrap'><input type='range' id='tune-fps' min='1' max='30' value='25' oninput='document.getElementById(\"fps-disp\").innerText=this.value+\" FPS\"' onchange='updateParams()'><span id='fps-disp' style='width:60px; font-family:monospace; font-weight:700'>25 FPS</span></div></div>"
"        </div>"
"        <div class='card'><h4>Stream Metrics</h4><div id='metrics-list' style='margin-top:16px'></div></div>"
"      </div>"
"    </section>"
"    <section id='config'><h2>System Configuration</h2><p style='color:var(--text-dim);margin-bottom:32px'>Modify core pipeline settings. Changes require a restart of the GStreamer pipelines.</p>"
"      <div class='card' style='max-width:600px'>"
"        <div class='form-group'><label>Active Lens</label><select id='cfg-lens' style='width:100%'><option value='lens1'>Primary Lens (/dev/video3)</option><option value='lens2'>Secondary Lens (/dev/video4)</option></select></div>"
"        <div class='form-group'><label>Target Branch</label><select id='cfg-tier' style='width:100%'><option value='main'>Main Stream (High Quality)</option><option value='sub'>Sub Stream (Standard)</option><option value='third'>Third Stream (Efficient/MJPEG)</option></select></div>"
"        <div class='form-group'><label>Resolution Tier</label><select id='cfg-res' style='width:100%'><option value='1920x1080'>1080p Full HD</option><option value='1280x720'>720p HD</option><option value='640x480'>480p SD</option></select></div>"
"        <div class='form-group'><label>Hardware Compression</label><select id='cfg-enc' style='width:100%'><option value='h264'>H.264 (Hardware)</option><option value='h265'>H.265 (Hardware)</option><option value='h264_sw'>H.264 (Software CPU)</option><option value='mjpeg'>MJPEG (Software CPU)</option></select></div>"
"        <button style='background:var(--accent); color:white; width:100%; padding:14px' onclick='applyConfig()'>Rebuild Pipeline</button>"
"      </div>"
"    </section>"
"    <section id='recordings'>"
"      <h2>Recording Management</h2><p style='color:var(--text-dim);margin-bottom:32px'>Manage active DVR sessions and saved clips.</p>"
"      <div class='card' style='margin-bottom:40px'>"
"        <h4 style='border-bottom:1px solid var(--border); padding-bottom:12px; margin-bottom:20px'>Active Recorders</h4>"
"        <div id='active-recordings-list'><i>No active recordings running.</i></div>"
"      </div>"
"      <h4 style='margin-bottom:20px'>Saved Cloud Recordings</h4>"
"      <div class='recordings-grid' id='rec-list'></div>"
"    </section>"
"    <section id='advanced'><h2>Engine Diagnostics</h2><div class='card'><pre id='engine-log' style='font-family:monospace; font-size:0.8rem; height:400px; overflow-y:auto; color:var(--text-dim)'></pre></div></section>"
"  </main>"
"<script>"
"  let state = { token: localStorage.getItem('token'), lens: 'lens1', tier: 'main', isRec: false };\n"
"  const api = (u, m='GET', b=null) => fetch(u, { method: m, headers: { 'Authorization': 'Bearer '+state.token, 'Content-Type': 'application/json' }, body: b ? JSON.stringify(b) : null }).then(r => r.json());\n"
"  function doLogin() {\n"
"    try {\n"
"      const u = document.getElementById('user').value; const p = document.getElementById('pass').value;\n"
"      fetch('/api/v1/auth/login', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({ username: u, password: p }) })\n"
"      .then(r => { if(!r.ok && r.status !== 401) throw new Error('HTTP '+r.status); return r.json(); })\n"
"      .then(d => {\n"
"        if(d.token) { state.token = d.token; localStorage.setItem('token', d.token); init(); }\n"
"        else { document.getElementById('login-error').style.display='block'; document.getElementById('login-error').innerText = d.error || 'Access Denied: Invalid Credentials'; }\n"
"      })\n"
"      .catch(e => { document.getElementById('login-error').style.display='block'; document.getElementById('login-error').innerText = 'Network Error: ' + e.message; });\n"
"    } catch(err) { document.getElementById('login-error').style.display='block'; document.getElementById('login-error').innerText = 'Sync Error: ' + err.message; }\n"
"  }\n"
"  function logout() { localStorage.removeItem('token'); location.reload(); }"
"  function switchTab(t) {"
"    document.querySelectorAll('section').forEach(s => s.classList.remove('active'));"
"    document.querySelectorAll('.nav-item').forEach(i => i.classList.toggle('active', i.innerText.toLowerCase().includes(t.toLowerCase())));"
"    document.getElementById(t).classList.add('active');"
"    if(t == 'live') loadPlayer();"
"    if(t == 'recordings') loadRecords();"
"  }"
"  function init() {"
"    if(!state.token) return;"
"    document.getElementById('login-overlay').style.display='none';"
"    api('/api/v1/system/status').then(d => {"
"      let sel = document.getElementById('stream-selector'); sel.innerHTML = '';"
"      Object.keys(d.lenses).forEach(lid => { ['main','sub','third'].forEach(tier => {"
"        if(!d.lenses[lid].branches[tier]) return;"
"        let btn = document.createElement('button'); btn.className = 'tab-btn'; btn.innerText = lid+' '+tier; btn.onclick = () => { state.lens=lid; state.tier=tier; loadPlayer(); };"
"        sel.appendChild(btn);"
"      }); });"
"      loadPlayer();"
"    });"
"  }"
"  let hls = null;\n"
"  function loadPlayer() {\n"
"    let v = document.getElementById('video'); let u = '/api/v1/stream/'+state.lens+'/'+state.tier+'/playlist.m3u8?token='+state.token;\n"
"    document.querySelectorAll('.tab-btn').forEach(b => b.classList.toggle('active', b.innerText == state.lens+' '+state.tier));\n"
"    if(hls) hls.destroy();\n"
"    if(Hls.isSupported()){\n"
"      hls = new Hls({ liveSyncDurationCount: 2, maxLiveSyncPlaybackRate: 2, lowLatencyMode: true, xhrSetup: (x) => x.setRequestHeader('Authorization', 'Bearer '+state.token) });\n"
"      hls.loadSource(u); hls.attachMedia(v); hls.on(Hls.Events.MANIFEST_PARSED, () => v.play());\n"
"    } else if(v.canPlayType('application/vnd.apple.mpegurl')) { v.src = u; v.play(); }\n"
"    updateStatusCard();\n"
"  }\n"
"  function updateStatusCard() {\n"
"    api('/api/v1/system/status').then(d => {\n"
"      if(document.getElementById('total-clients')) document.getElementById('total-clients').innerText = d.total_clients;\n"
"      const l = d.lenses[state.lens]; const b = l && l.branches[state.tier];\n"
"      if(!b) return;\n"
"      state.isRec = b.recording;\n"
"      const btn = document.getElementById('rec-toggle-btn'); if(btn){ btn.innerText = state.isRec ? '■ STOP RECORD' : '● RECORD'; btn.style.background = state.isRec ? 'var(--danger)' : 'rgba(0,0,0,0.5)'; }\n"
"      const m = document.getElementById('metrics-list'); m.innerHTML = `<div class='stat-row'><span class='stat-label'>Device</span><span>${l.device}</span></div><div class='stat-row'><span class='stat-label'>Resolution</span><span>${b.resolution}</span></div><div class='stat-row'><span class='stat-label'>Framerate</span><span>${b.fps} FPS</span></div><div class='stat-row'><span class='stat-label'>Encoder</span><span>${b.encoder.toUpperCase()}</span></div>`;\n"
"      document.getElementById('overlay-info').innerText = `${b.resolution} | ${b.fps} FPS`;\n"
"      "
"      /* Update the active recordings panel */\n"
"      let arc = document.getElementById('active-recordings-list');\n"
"      if(arc) {\n"
"        let acts = [];\n"
"        Object.keys(d.lenses).forEach(lid => { Object.keys(d.lenses[lid].branches).forEach(t => { if(d.lenses[lid].branches[t].recording) acts.push({l:lid, t:t}); }); });\n"
"        if(acts.length == 0) { arc.innerHTML = '<i>No active recordings running.</i>'; } else {\n"
"          arc.innerHTML = acts.map(a => `<div style='display:flex; justify-content:space-between; align-items:center; padding:12px; background:rgba(0,0,0,0.3); border-radius:8px; margin-bottom:10px;'><div><b>${a.l} / ${a.t}</b> <span style='color:var(--danger); font-size:0.8rem; margin-left:10px'>● RECORDING</span></div><button onclick=\"api('/api/v1/lenses/${a.l}/recording', 'DELETE').then(updateStatusCard)\" style='background:var(--border); font-size:0.8rem; padding:6px 12px'>Stop</button></div>`).join('');\n"
"        }\n"
"      }\n"
"    });\n"
"  }\n"
"  function toggleRecording() {\n"
"    const m = state.isRec ? 'DELETE' : 'POST'; api('/api/v1/lenses/'+state.lens+'/recording', m).then(() => setTimeout(updateStatusCard, 1000));\n"
"  }\n"
"  function updateParams() {\n"
"    const fps = parseInt(document.getElementById('tune-fps').value);\n"
"    const br = parseInt(document.getElementById('tune-bitrate').value);\n"
"    const res = document.getElementById('tune-res').value;\n"
"    let payload = { fps, bitrate: br }; if(res) payload.resolution = res;\n"
"    api('/api/v1/lenses/'+state.lens+'/params/'+state.tier, 'PATCH', payload).then(updateStatusCard);\n"
"  }\n"
"  function applyConfig() {\n"
"    const l = document.getElementById('cfg-lens').value; const t = document.getElementById('cfg-tier').value; const r = document.getElementById('cfg-res').value; const e = document.getElementById('cfg-enc').value;\n"
"    api('/api/v1/lenses/'+l+'/config', 'PATCH', { lens: l, [t]: { resolution: r, encoder: e } }).then(() => alert('Pipeline update command sent to GStreamer.'));\n"
"  }\n"
"  function loadRecords() {\n"
"    api('/api/v1/recordings').then(d => {\n"
"      let l = document.getElementById('rec-list'); l.innerHTML = '';\n"
"      d.recordings.sort().reverse().forEach(f => {\n"
"        let c = document.createElement('div'); c.className = 'rec-card'; c.innerHTML = `<div style='font-size:0.8rem; margin-bottom:12px'>${f}</div><div style='display:flex;gap:10px'><a href='/recordings/${f}' target='_blank' class='tab-btn' style='font-size:0.75rem;flex:1;text-align:center'>VIEW</a><button onclick=\"delRec('${f}')\" style='background:var(--danger);color:white;padding:4px 10px;font-size:0.7rem'>DEL</button></div>`;\n"
"        l.appendChild(c);\n"
"      });\n"
"    });\n"
"  }\n"
"  function delRec(f) { if(confirm('Permanent Delete '+f+'?')) api('/api/v1/recordings/'+f, 'DELETE').then(loadRecords); }\n"
"  function takeSnapshot() { api('/api/v1/lenses/'+state.lens+'/snapshot', 'POST').then(d => alert('Snapshot captured: '+d.file)); }\n"
"  if(state.token) init();\n"
"  setInterval(() => { if(document.getElementById('live').classList.contains('active')) updateStatusCard(); }, 3000);\n"
"  setInterval(() => { if(state.token) { let t = document.getElementById('stream-timer'); let n = new Date(); t.innerText = n.toTimeString().split(' ')[0]; } }, 1000);\n"
"</script></body></html>";

#endif
